askbot/setup_templates/urls.py
"""
main url configuration file for the askbot site
"""
from django.conf import settings
try:
    from django.conf.urls import handler404
    from django.conf.urls import include, patterns, url
except ImportError:
    from django.conf.urls.defaults import handler404
    from django.conf.urls.defaults import include, patterns, url

from askbot.views.error import internal_error as handler500
from django.conf import settings
from django.contrib import admin

admin.autodiscover()

if getattr(settings, 'ASKBOT_MULTILINGUAL', False) == True:
    from django.conf.urls.i18n import i18n_patterns
    urlpatterns = i18n_patterns('',
        (r'%s' % settings.ASKBOT_URL, include('askbot.urls'))
    )
else:
    urlpatterns = patterns('',
        (r'%s' % settings.ASKBOT_URL, include('askbot.urls'))
    )

urlpatterns += patterns('',
    (r'^admin/', include(admin.site.urls)),
    #(r'^cache/', include('keyedcache.urls')), - broken views disable for now
    #(r'^settings/', include('askbot.deps.livesettings.urls')),
    (r'^followit/', include('followit.urls')),
    (r'^tinymce/', include('tinymce.urls')),
    (r'^robots.txt$', include('robots.urls')),
    url( # TODO: replace with django.conf.urls.static ?
        r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:],
        'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT.replace('\\','/')},
    ),
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
                    url(r'^rosetta/', include('rosetta.urls')),
                )

handler500 = 'askbot.views.error.internal_error'

askbot/urls.py
        kwargs={'reason':'bad','action':'add'},
        name='mark_ignored_tag'
    ),
    service_url(#ajax only
        r'^%s%s$' % ('mark-tag/', 'subscribed/'),
        views.commands.mark_tag,
        kwargs={'reason':'subscribed','action':'add'},
        name='mark_subscribed_tag'
    ),
    service_url(#ajax only
        r'^unmark-tag/',
        views.commands.mark_tag,
        kwargs={'action':'remove'},
        name='unmark_tag'
    ),
    service_url(#ajax only
        r'^set-tag-filter-strategy/',
        views.commands.set_tag_filter_strategy,
        name = 'set_tag_filter_strategy'
    ),
    service_url(
        r'^get-tags-by-wildcard/',
        views.commands.get_tags_by_wildcard,
        name = 'get_tags_by_wildcard'
    ),
    service_url(
        r'^get-tag-list/',
        views.commands.get_tag_list,
        name = 'get_tag_list'
    ),
    service_url(
        r'^load-object-description/',
        views.commands.load_object_description,
        name = 'load_object_description'
    ),
    service_url(#ajax only
        r'^save-object-description/',
        views.commands.save_object_description,
        name = 'save_object_description'
    ),
    service_url(#ajax only
        r'^add-tag-category/',
        views.commands.add_tag_category,
        name = 'add_tag_category'
    ),
    service_url(#ajax only
        r'^rename-tag/',
        views.commands.rename_tag,
        name = 'rename_tag'
    ),
    service_url(#
        r'^delete-tag/',
        views.commands.delete_tag,
        name = 'delete_tag'
    ),
    service_url(#ajax only
        r'^save-group-logo-url/',
        views.commands.save_group_logo_url,
        name = 'save_group_logo_url'
    ),
    service_url(#ajax only
        r'^delete-group-logo/',
        views.commands.delete_group_logo,
        name = 'delete_group_logo'
    ),
    service_url(#ajax only
        r'^add-group/',
        views.commands.add_group,
        name = 'add_group'
    ),
    service_url(#ajax only
        r'^toggle-group-profile-property/',
        views.commands.toggle_group_profile_property,
        name='toggle_group_profile_property'
    ),
    service_url(#ajax only
        r'^set-group-openness/',
        views.commands.set_group_openness,
        name='set_group_openness'
    ),
    service_url(#ajax only
        r'^edit-object-property-text/',
        views.commands.edit_object_property_text,
        name = 'edit_object_property_text'
    ),
    service_url(
        r'^get-groups-list/',
        views.commands.get_groups_list,
        name = 'get_groups_list'
    ),
    service_url(
        r'^toggle-follow-question/',
        views.commands.toggle_follow_question,
        name='toggle_follow_question'
    ),
    service_url(
        r'^swap-question-with-answer/',
        views.commands.swap_question_with_answer,
        name = 'swap_question_with_answer'
    ),
    service_url(
        r'^subscribe-for-tags/$',
        views.commands.subscribe_for_tags,
        name = 'subscribe_for_tags'
    ),
    service_url(
        r'get-html-template/',
        views.commands.get_html_template,
        name='get_html_template'
    ),
    service_url(#ajax only
        r'^messages/markread/$',
        views.commands.read_message,
        name='read_message'
    ),
    service_url(#ajax only
        r'^clear-new-notifications/$',
        views.users.clear_new_notifications,
        name='clear_new_notifications'
    ),
    service_url(#ajax_only
        r'^delete-notifications/$',
        views.users.delete_notifications,
        name='delete_notifications'
    ),
    service_url(#ajax only
        r'^save-post-reject-reason/$',
        views.commands.save_post_reject_reason,
        name='save_post_reject_reason'
    ),
    service_url(#ajax only
        r'^delete-post-reject-reason/$',
        views.commands.delete_post_reject_reason,
        name='delete_post_reject_reason'
    ),
    service_url(#ajax only
        r'^edit-group-membership/$',
        views.commands.edit_group_membership,
        name='edit_group_membership'
    ),
    service_url(#ajax only
        r'^join-or-leave-group/$',
        views.commands.join_or_leave_group,
        name = 'join_or_leave_group'
    ),
    #widgets url!
    service_url(
        r'^%s$' % (pgettext('urls', 'widgets/')),
        views.widgets.widgets,
        name = 'widgets'
    ),
    service_url(
        r'^%s%s(?P<widget_id>\d+)/$' % (
            pgettext('urls', 'widgets/'),
            pgettext('urls', 'ask/')
        ),
        views.widgets.ask_widget,
        name = 'ask_by_widget'
    ),
    service_url(
        r'^%s%s(?P<widget_id>\d+).js$' % (
            pgettext('urls', 'widgets/'),
            pgettext('urls', 'ask/')
        ),
        views.widgets.render_ask_widget_js,
        name = 'render_ask_widget'
    ),
    service_url(
        r'^%s%s(?P<widget_id>\d+).css$' % (
            pgettext('urls', 'widgets/'),
            pgettext('urls', 'ask/')
        ),
        views.widgets.render_ask_widget_css,
        name = 'render_ask_widget_css'
    ),
    service_url(
        r'^%s%s%s$' % (
            pgettext('urls', 'widgets/'),
            pgettext('urls', 'ask/'),
            pgettext('urls', 'complete/')
        ),
        views.widgets.ask_widget_complete,
        name = 'ask_by_widget_complete'
    ),
    service_url(
        r'^%s(?P<model>\w+)/%s$' % (
            pgettext('urls', 'widgets/'),
            pgettext('urls', 'create/')
        ),
        views.widgets.create_widget,
        name = 'create_widget'
    ),
    service_url(
        r'^%s(?P<model>\w+)/%s(?P<widget_id>\d+)/$' % (
            pgettext('urls', 'widgets/'),
            pgettext('urls', 'edit/')
        ),
        views.widgets.edit_widget,
        name = 'edit_widget'
    ),
    service_url(
        r'^%s(?P<model>\w+)/%s(?P<widget_id>\d+)/$' % (
            pgettext('urls', 'widgets/'),
            pgettext('urls', 'delete/')
        ),
        views.widgets.delete_widget,
        name = 'delete_widget'
    ),
    service_url(
        r'^%s(?P<model>\w+)/$' % (pgettext('urls', 'widgets/')),
        views.widgets.list_widgets,
        name = 'list_widgets'
    ),
    service_url(
        r'^widgets/%s(?P<widget_id>\d+)/$' % MAIN_PAGE_BASE_URL,
        views.widgets.question_widget,
        name='question_widget'
    ),
    service_url(
        r'^get-perms-data/$',
        views.readers.get_perms_data,
        name='get_perms_data'
    ),
    service_url(
        r'^start-sharing-twitter/$',
        views.sharing.start_sharing_twitter,
        name='start_sharing_twitter'
    ),
    service_url(
        r'^save-twitter-access-token/$',
        views.sharing.save_twitter_access_token,
        name='save_twitter_access_token'
    ),
    service_url(#ajax post only
        r'^change-social-sharing-mode/$',
        views.sharing.change_social_sharing_mode,
        name='change_social_sharing_mode'
    ),
    #upload url is ajax only
    service_url(
        r'^%s$' % pgettext('urls', 'upload/'),
        views.writers.upload,
        name='upload'
    ),
    service_url(
        r'^doc/(?P<path>.*)$',
        'django.views.static.serve',
        {'document_root': os.path.join(APP_PATH,'doc','build','html').replace('\\','/')},
        name='askbot_docs',
    ),
    service_url(
        r'^jsi18n/$',
        'django.views.i18n.javascript_catalog',
        {'domain': 'djangojs','packages': ('askbot',)},
        name = 'askbot_jsi18n'
    ),
    service_url(r'^private-messages/', include('askbot.deps.group_messaging.urls')),
    service_url(r'^settings/', include('livesettings.urls')),
    service_url(r'^preview-emails/$', views.emails.list_emails, name='list_emails'),
    service_url(r'^preview-emails/(?P<slug>.+)/$', views.emails.preview_email, name='preview_email'),

    service_url('^api/v1/info/$', views.api_v1.info, name='api_v1_info'),
    service_url('^api/v1/users/$', views.api_v1.users, name='api_v1_users'),
    service_url('^api/v1/users/(?P<user_id>\d+)/$', views.api_v1.user, name='api_v1_user'),
    service_url('^api/v1/questions/$', views.api_v1.questions, name='api_v1_questions'),
    service_url('^api/v1/questions/(?P<question_id>\d+)/$', views.api_v1.question, name='api_v1_question'),
)

if 'askbot.deps.django_authopenid' in settings.INSTALLED_APPS:
    urlpatterns += (
        service_url(
            r'^%s' % pgettext('urls', 'account/'),
            include('askbot.deps.django_authopenid.urls')
        ),
    )

if 'avatar' in settings.INSTALLED_APPS:
    urlpatterns += (
        #avatar views are added here, because some need
        #either dynamic extra context or custom redirect
        #or extra parameter in the urls
        service_url(
            '^avatar/upload/(?P<user_id>\d+)/$',
            views.avatar_views.upload,
            name='askbot_avatar_upload'
        ),
        service_url(
            '^avatar/list/(?P<user_id>\d+)/$',
            views.avatar_views.show_list,
            name='askbot_avatar_show_list'
        ),
        service_url(
            '^avatar/set-primary/(?P<user_id>\d+)/$',
            views.avatar_views.set_primary,
            name='askbot_avatar_set_primary'
        ),
        service_url(
            '^avatar/delete/(?P<avatar_id>\d+)/$',
            views.avatar_views.delete,
            name='askbot_avatar_delete'
        ),
        service_url(#this url is used without changes as in the avatar app
            '^avatar/render-primary/(?P<user>[\w\d\.\-_]+)/(?P<size>[\d]+)/$',
            'avatar.views.render_primary',
            name='avatar_render_primary'
        ),
        service_url(
            '^avatar/enable-gravatar/(?P<user_id>[\d]+)/$',
            views.avatar_views.enable_gravatar,
            name='askbot_avatar_enable_gravatar'
        ),
        service_url(
            '^avatar/enable-default-avatar/(?P<user_id>[\d]+)/$',
            views.avatar_views.enable_default_avatar,
            name='askbot_avatar_enable_default_avatar'

askbot/models/widgets.py
from django.db import models
from django.utils.translation import ugettext_lazy
from askbot.models import Tag, Group
from askbot.const import DEFAULT_QUESTION_WIDGET_STYLE, SEARCH_ORDER_BY

class AskWidget(models.Model):
    '''stores widgets styles and options'''
    title = models.CharField(max_length=100)
    group = models.ForeignKey(Group, null=True, blank=True)
    tag = models.ForeignKey(Tag, null=True, blank=True)

    include_text_field = models.BooleanField(default=False, blank=True)

    inner_style = models.TextField(blank=True)
    outer_style = models.TextField(blank=True)

    class Meta:
        app_label = 'askbot'

    def __unicode__(self):
        return u"Widget: %s" % self.title


class QuestionWidget(models.Model):
    title = models.CharField(max_length=100)
    question_number = models.PositiveIntegerField(default=7)
    tagnames = models.CharField(ugettext_lazy('tags'), max_length=50)
    group = models.ForeignKey(Group, null=True, blank=True)
    search_query = models.CharField(
        max_length=50, null=True, blank=True, default=''
    )
    order_by = models.CharField(max_length=18,
            choices=SEARCH_ORDER_BY, default='-added_at')
    style = models.TextField(ugettext_lazy('css for the widget'),
            default=DEFAULT_QUESTION_WIDGET_STYLE, blank=True)

    class Meta:
        app_label = 'askbot'

askbot/templates/embed/ask_by_widget.html
{% extends "widget_base.html" %}
{% import "macros.html" as macros %}
{% block forestyle %}
    {% if editor_type == 'markdown' %}
        {% compress css %}
        <link rel="stylesheet" type="text/css" href="{{ '/wmd/wmd.css'|media }}" />
        {% endcompress %}
    {% else %}
        {% compress css %}
        <link href="{{ '/bootstrap/css/bootstrap.css'|media }}" rel="stylesheet" type="text/css" />
        {% endcompress %}
    {% endif %}
{% include "meta/fonts.html" %}
<style type="text/css" media="screen">
body{
    font-family: Verdana, Arial, Helvetica, sans-serif;
}
#editor {
    display: block;
    min-height: 200px;
    width: 98%;
    margin: 0;
    border:none;
    outline:none;
    padding: 6px;
}
.wmd-container{
    border: #CCE6EC 3px solid;
    width: 100%;
    margin-top: 20px;
}

#id_title{
    {% if editor_type == 'markdown' %}
        width: 100%;
    {% else %}
        padding: 0px 0 0 5px;
        width: 99.2%;
    {% endif %}
    font-size: 130%;
    border: #CCE6EC 3px solid;
    max-width: 600px;
}

#id_title:focus {
    outline: none;
    box-shadow: none;
}

.title{
    font-family: 'Open Sans Condensed', Arial, sans-serif;
    font-size: 25px;
    margin-bottom: 10px;
}

#question-list {
    height: auto;
    z-index: 10000;
    position: absolute;
    border: 3px solid #CCE6EC;
    border-top:none;
    -webkit-border-radius: 3px;
    -moz-border-radius: 3px;
    border-radius: 3px;
    background: #fff;
    {% if editor_type == 'markdown' %}
        width: 97.4%;
    {% else %}
        width: 90.8%;
    {% endif %}
    margin-top: -4.9px;
}

#question-list h2{
    text-decoration: none;
    margin: 0px;
    font-size: 13px;
    padding: 3px 0 3px 5px;
    padding-bottom: 0;
    border-top: #F0F0EC 1px solid;
    min-height: 30px;
    line-height: 30px;
    font-weight: normal
}

#question-list h2:first-child{
    border-top: none;
}

#question-list a{
    color: #005580;
}

#question-list a:hover{
    color: #005580;
    text-decoration: underline;
}

#question-list a:visited{
    color: #005580;
    text-decoration: none;
}

#question-list span{
    width: 28px;
    height: 26px;
    line-height: 26px;
    text-align: center;
    margin-right: 10px;
    float: left;
    display: block;
    color: white;
    background: #B8D0D5;
    border-radius: 3px;
    -ms-border-radius: 3px;
    -moz-border-radius: 3px;
    -webkit-border-radius: 3px;
    -khtml-border-radius: 3px;
}
{% if editor_type == 'markdown' %}
#wmd-button-bar {
    background: url({{"/jslib/wmd/images/editor-toolbar-background.png"|media}}) repeat-x bottom;
    height: 30px;
    border: 0;
    display: block;
}
{% endif %}

#submit{
    font-size: 130%;
    margin-right: -6px;
    float: right;
    text-align: center;
    text-decoration: none;
    cursor: pointer;
    color: #4A757F;
    font-family: 'Open Sans Condensed', Arial, sans-serif;
    text-shadow: 0px 1px 0px #C6D9DD;
    -moz-text-shadow: 0px 1px 0px #c6d9dd;
    -webkit-text-shadow: 0px 1px 0px #c6d9dd;
    border-top: #EAF2F3 1px solid;
    background-color: #D1E2E5;
    background-repeat: no-repeat;
    background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#D1E2E5), color-stop(25%, #D1E2E5), to(#A9C2C7));
    background-image: -webkit-linear-gradient(#D1E2E5, #D1E2E5 25%, #A9C2C7);
    background-image: -moz-linear-gradient(top, #D1E2E5, #D1E2E5 25%, #A9C2C7);
    background-image: -ms-linear-gradient(#D1E2E5, #D1E2E5 25%, #A9C2C7);
    background-image: -o-linear-gradient(#D1E2E5, #D1E2E5 25%, #A9C2C7);
    background-image: linear-gradient(#D1E2E5, #D1E2E5 25%, #A9C2C7);
    border-radius: 4px;
    -ms-border-radius: 4px;
    -moz-border-radius: 4px;
    -webkit-border-radius: 4px;
    -khtml-border-radius: 4px;
    -webkit-box-shadow: 1px 1px 2px #636363;
    -moz-box-shadow: 1px 1px 2px #636363;
    box-shadow: 1px 1px 2px #636363;
    width: 200px;
}

.field-errors{
    font-size: 10px;
    color: #ff0000;
    height: 10px;
}
{{ widget.inner_style }}
</style>
{% endblock %}

{% block body %}
    <div class="title">{{ widget.title }}</div>
    <form action="." method="POST" accept-charset="utf-8">
        {% csrf_token %}
        <label>{{ settings.WORDS_PLEASE_ENTER_YOUR_QUESTION|escape }}</label>
        <div class="input-title">{{ form.title }}</div>
        <div id='question-list'></div>
        <div class="field-errors">
            {% for error in form.title.errors %} {{ error }} {% endfor %}
        </div>
    {% if widget.include_text_field %}
        {% if editor_type == 'markdown' %}
        <div class="wmd-container">
            <div id="wmd-button-bar" class="wmd-panel"></div>
            {{ form.text }}{# this element is resizable and will be wrapped by js #}
        </div>
        {% else %}
        <div class="wmd-container">
            {{ form.media }}
            {{ form.text }}
        </div>
        {% endif %}
        <div class="field-errors">
            {% for error in form.text.errors %}{{ error }}{% endfor %}
        </div>
    {% endif %}
        {% if form.ask_anonymously %}
        <p>{{ form.ask_anonymously.label_tag() }}: {{ form.ask_anonymously }}</p>
    {% endif %}
        <input type="submit" value="{{ settings.WORDS_ASK_YOUR_QUESTION|escape }}" id="submit" />
    </form>
{% endblock %}
{% block endjs %}
    {% compress js %}
    <script type="text/javascript" src="{{ '/jslib/editor.js'|media }}"></script>
    {% endcompress %}
    {% if editor_type == 'markdown' %}
        {% include "meta/markdown_javascript.html" %}
    {% else %}
        {% include "meta/tinymce_css.html" %}{# todo - maybe move to form media? #}
    {% endif %}
    {% compress js %}
    <script type="text/javascript" src="{{ '/js/live_search_new_thread.js'|media }}"></script>
    {% endcompress %}
    <script type="text/javascript" charset="utf-8">
        askbot['settings']['minSearchWordLength'] = {{ min_search_word_length }};
        askbot['urls']['apiGetQuestions'] = '{% url "api_get_questions" %}';
        askbot['urls']['upload'] = '{% url upload %}';
        $(document).ready(function(){
            var searchInput = $('#id_title');
            searchInput.addClass('questionTitleInput');
            var search = new FullTextSearch();
            search.decorate(searchInput);
            searchInput.focus();
        });
    </script>
{% endblock %}

askbot/templates/embed/ask_widget_complete.html
{% extends "widget_base.html" %}
{% block forestyle %}
{%endblock%}

{%block body%}
<a href="{{question_url}}" target="_blank" >Question posted</a>
{%endblock%}

askbot/templates/embed/delete_widget.html
{% extends "one_column_body.html" %}
<!-- create_ask_widget.html -->
{% block title %}Delete {{widget_name|capitalize}} Widget{% endblock %}
{% block content %}
<h1>Are you sure that you cant to delete this {{widget_name|capitalize}}Widget?</h1>
<br/>
<strong>Warning: This could break the widgets on sites that currently use this widget please make sure that you don't use the widget in other sites</strong>
<form action="." method="POST">{% csrf_token %}
  <p><input type='submit' value='Delete' /> <a href="{% url list_widgets widget_name %}">Go Back</a></p>
</form>
{% endblock %}
{% block endjs %}
{% endblock %}

askbot/templates/embed/list_widgets.html
{% extends "two_column_body.html" %}
<!-- create_ask_widget.html -->
{% block title %}{{ widget_name|capitalize }} widget list{% endblock %}
{% block content %}
<h1>{% trans type=widget_name|capitalize %}{{ type }} widget list{% endtrans %}</h1>
<table>
    <tr>
        <th>{% trans %}Widget Title{% endtrans %}</th>
        <th>{% trans %}Code{% endtrans %}</th>
        <th>{% trans %}Actions{% endtrans %}</th>
    </tr>
    {% if request.is_secure() %}
        {% set protocol='https' %}
    {% else %}
        {% set protocol='http' %}
    {% endif %}
    {% if widget_name == 'ask' %}
        {% for widget in widgets %}
        <tr>
            <td>{{ widget.title }}</td>
            <td>&lt;script type="text/javascript" src="{{ protocol }}://{{ request.get_host() }}{% url render_ask_widget widget.id %}" &gt;&lt;/script&gt;</td> 
            <td>
                <a href="{% url edit_widget widget_name, widget.id %}">{% trans %}Edit{% endtrans %}</a> | 
                <a href="{% url delete_widget widget_name, widget.id %}">{% trans %}Delete{% endtrans %}</a>
            </td>
        </tr>
        {% endfor %}
    {% else %}
        {% for widget in widgets %}
        <tr>
            <td>{{ widget.title }}</td>
            <td> &lt;iframe src="{{ protocol }}://{{ request.get_host() }}{% url question_widget widget.id %}" &gt; &lt;/iframe&gt;</td> 
            <td>
                <a href="{% url edit_widget widget_name, widget.id %}">{% trans %}Edit{% endtrans %}</a> |
                <a href="{% url delete_widget widget_name, widget.id %}">{% trans %}Delete{% endtrans %}</a>
            </td>
        </tr>
        {% endfor %}
    {% endif %}
</table>
{% endblock %}

{% block endjs %}
{% endblock %}

{% block sidebar %}
<div class="box">
    <h2>{% trans %}How to use?{% endtrans %}</h2>
    <p>
        {% trans %}Just copy the &lt;script&gt; tag provided and paste it in the site where you wan to put it.{% endtrans %} 
    </p>
</div>
{% endblock %}

askbot/templates/embed/question_widget.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <style type="text/css">
        {{widget.style|safe}}
    </style>
</head>
<body>
    {{widget.title|safe}}
    <div id="container">
        <ul>
            {% for thread in threads %}
                <li><a href="{{settings.APP_URL|strip_path}}{{ thread.get_absolute_url() }}" target="_blank">
                  {{ thread.title|escape }}</a></li>
            {% endfor %}
        </ul>
    </div> 
</body>
</html>

askbot/templates/embed/widget_form.html
{% extends "one_column_body.html" %}
<!-- create_ask_widget.html -->
{% block title %}{% trans %}{{action}} an {{widget_name}} widget{% endtrans %}{% endblock %}
{% block content %}
<h1 class="section-title">{% trans %}{{action}} an {{widget_name}} widget{% endtrans %}</h1>
{#% if form.non_field_errors() %}
  {{ form.non_field_errors() }}
{% endif %#}
<form method="post">{% csrf_token %}
    <table>
        {{ form.as_table() }}
        <tr>
            <td colspan="2" style="text-align: center">
                <input type="submit" value={% trans %}Save{% endtrans %} />
            </td>
        </tr>
    </table>
</form>

{% endblock %}
{% block endjs %}
{% endblock %}

askbot/templates/embed/widgets.html
{% extends "one_column_body.html" %}
<!-- template badges.html -->
{% block title %}{% spaceless %}{% trans %}Widgets{% endtrans %}{% endspaceless %}{% endblock %}
{% block content %}
<h1 class="section-title">{% trans %}Widgets{% endtrans %}</h1>
<p>
</p>
<table>
    <thead>
        <th colspan="3">
            {% trans %}Create and embed widgets into your sites, here a list of available widgets.{% endtrans %}
        </th>
    </thead>
    <tbody>
        <tr>
            <td>"{{ settings.WORDS_ASK_YOUR_QUESTION|escape }}"</td>
            <td><a href="{% url create_widget 'ask' %}">{% trans %}create{% endtrans %}</a></td>
            <td>
                {% if ask_widgets > 0 %}
                    <a href="{% url list_widgets 'ask' %}">{% trans %}view list{% endtrans %}</a>
                {% endif %}
            </td>
        </tr>
        <tr>
        <td>{{ settings.WORDS_LIST_OF_QUESTIONS|escape }}</td>
            <td><a href="{% url create_widget 'question' %}">{% trans %}create{% endtrans %}</a></td>
            <td>
                {% if question_widgets > 0 %}
                    <a href="{% url list_widgets 'question' %}">{% trans %}view list{% endtrans %}</a>
                {% endif %}
            </td>
        </tr>
    </tbody>
</table>
{% endblock %}
<!-- end template badges.html -->